name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          ech0 $GITHUB_REPOSITORY
          echo $GITHUB_WORKPLACE
          echo $"${{ github.token }}"
          git clone git@github:$GITHUB_REPOSITORY
      - name: checkout
        uses: actions/checkout@v1
      - name: simple js actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
